user:
  name:
    max_length: 40
  email:
    max_length: 127
  password:
    min_length: 8
    reset_time_expired: 24
  helper:
    gravatar:
      size: 80
    post_per_page: 10
  index:
    per_page: 7
micropost:
  content:
    max_length: 160
  gravatar:
    size: 50
